# Generated by Django 4.1.5 on 2023-02-10 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Salon1', '0011_laser_epilation_category_laser_epilation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promoution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(null=True)),
                ('size', models.PositiveIntegerField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Salon1.category_service')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Salon1.type_service')),
            ],
        ),
    ]
