# Generated by Django 4.1.5 on 2023-02-12 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon1', '0011_laser_epilation_category_laser_epilation_type'),
        ('Promoution', '0002_promoution_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoution',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Salon1.gender'),
        ),
    ]
