# Generated by Django 4.1.5 on 2023-02-04 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='base64',
            new_name='description',
        ),
    ]
