# Generated by Django 4.1.5 on 2023-02-05 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0002_rename_base64_shop_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='price',
            new_name='price1',
        ),
        migrations.AddField(
            model_name='shop',
            name='price2',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='volume1',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shop',
            name='volume2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
