# Generated by Django 4.1.5 on 2023-02-05 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_rename_price_shop_price1_shop_price2_shop_volume1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shop',
            old_name='price1',
            new_name='ref1',
        ),
        migrations.RenameField(
            model_name='shop',
            old_name='price2',
            new_name='ref2',
        ),
    ]
