# Generated by Django 4.1.5 on 2023-02-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_volume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='volume2',
        ),
        migrations.AlterField(
            model_name='shop',
            name='volume1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Shop.volume'),
        ),
    ]
