# Generated by Django 4.1.5 on 2023-02-05 12:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_shop_english_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ref1',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='shop',
            name='ref2',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
