# Generated by Django 4.1.5 on 2023-02-05 12:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_alter_shop_ref1_alter_shop_ref2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='ref2',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
