# Generated by Django 4.1.5 on 2023-02-07 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
