# Generated by Django 4.1.5 on 2023-02-12 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0012_delete_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['name', 'english_name']},
        ),
    ]
