# Generated by Django 4.1.5 on 2023-02-02 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon1', '0004_category_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='laser_epilation',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Salon1.category_service'),
        ),
    ]
