# Generated by Django 4.1.5 on 2023-02-02 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Salon1', '0007_alter_laser_epilation_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='laser_epilation',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Salon1.type_service'),
        ),
    ]
