# Generated by Django 4.1.5 on 2023-02-12 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Salon1', '0011_laser_epilation_category_laser_epilation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='type_service',
            name='info',
            field=models.TextField(blank=True),
        ),
    ]
